### ISSUE TITLE
Move grunt-browserify to gulp-browserify for easier migrate to gulptraum

### ISSUE THREAD

**Issue by moellenbeck** [process-engine/skeleton#17]
#### Describe your issue

Use a consistent build pipeline

#### How can others reproduce the issue?

n.a.

**Comment by heikomat** [comment]
@moellenbeck we should discuss with @5ebastianMeier if browserification should belong into the scope of gulptraum. If so, i'd love to see a clear definition of what gulptraum is, and what it is supposed to do, that includes browserification.

As much as using the same tools for similar tasks is useful for consistency, i wouldn't want gulptraum to become the "i do everything"-gulp-plugin that no one understands.

Remember: Do one thing, and do it well. I think this also applies to software, or at least to tooling. As long as we find a clear definition of gulptraum that includes browserification, i have no objection.

**Comment by moellenbeck** [comment]
@heikomat but @ first we should move from grunt to gulp //cc @5ebastianMeier

**Comment by heikomat** [comment]
As long as using gulp and gulp-browserify is just as simple as using grunt and grunt-browserify, you are correct and it seems to be more logical to use gulp. i'll check that tomorrow, shouldn't take long
