### ISSUE TITLE
Add general-purpose-entity to pi-server and browser-server

### ISSUE THREAD

**Issue by heikomat** [process-engine/skeleton#31]
#### Describe your issue

The general-purpose-entity `Store` is already implemented in the regular process-engine-server and the process-engine-server-demo, but process-engine-pi and process-engine-browser are still missing it. We need to add them.

#### How can others reproduce the issue?

The pi-version of the process-engine-skeleton won't be able to handle the StoreEntity

#### Possible solution

Add the StoreEntity to process-engine-pi and process-engine-browser

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
Feature has been merged -> closing...
