### ISSUE TITLE
Failing curl operation within Infinity loop clogs up jenkins build pipeline

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/skeleton#51]
#### Describe your issue

The jenkins build for the skeleton repo contains a script, which runs a curl operation, followed by a sleep-operation, wrapped in an infinity loop.

The curl **always fails**. But instead of cancelling the build, the infinity loop that is wrapped around the operation will cause the request to run again and again and again, probably until judgement day.

We have had a build that has run for **six days**!

This must be fixed ASAP, because this seriously compromises the build chain. 

#### How can others reproduce the issue?

Refer to any skeleton jenkins build. 
For example:
https://ci.process-engine.io/blue/organizations/jenkins/process-engine_node-lts%2Fskeleton/detail/master/91/pipeline

Sample Logoutput:
<img width="1612" alt="bildschirmfoto 2018-06-05 um 10 26 59" src="https://user-images.githubusercontent.com/15343316/40964289-067033bc-68ab-11e8-978d-caa9c341532c.png">

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
The build is broken since this build:

https://ci.process-engine.io/job/process-engine_node-lts/job/skeleton/job/master/88/

It seems that new commits pushed to master between 87 and 88:

82ccc1be74325561432c3890a839f7ae277a0bb8..1da9b71cd37cec53274e384e674bb414374b75d5

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/72

**Comment by Paulomart** [comment]
It seems that the build works is no longer broken.

Build 98 did pass successfull: https://ci.process-engine.io/job/process-engine_node-lts/job/skeleton/job/master/98/

Compare changes to master between 97 and 98:

https://github.com/process-engine/skeleton/compare/82ccc1be74325561432c3890a839f7ae277a0bb8...develop

**Comment by Paulomart** [comment]
To prevent this in the future we should add an timeout to these `while` expressions.

For example:

```groovy
timeout(20) {
  node {
    sh 'foo'
  }
}
```
